export type Stop = {
  id: string;
  itinerary_id: string;
  stop_order: number;
  name: string;
  start_time: string; // ISO timestamp
  end_time: string; // ISO timestamp
  description: string | null;
  google_maps_url: string | null;
  latitude: number | null;
  longitude: number | null;
  image_url: string | null;
  created_at: string;
};

// Shape used when inserting a new stop (id/created_at are generated by the DB)
export type NewStop = Omit<Stop, "id" | "created_at">;